#!/usr/bin/env bash
# Short Order asset pipeline runner.
# Regenerates every Blender asset and bakes them into public/short-order/assets.gen.js
# as base64 data-URIs (loaded via a <script> tag -> works on Pages AND file://).
#
#   bash tools/blender/build.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ASSETS="$ROOT/public/short-order/assets"
GEN="$ROOT/public/short-order/assets.gen.js"
mkdir -p "$ASSETS"

echo "== modelling in Blender =="
OUT="$ASSETS/plant.glb" blender --background --python "$ROOT/tools/blender/make_plant.py" 2>&1 | grep -E "WROTE|Error" || true

echo "== baking assets.gen.js =="
python3 - "$GEN" "$ASSETS" <<'PY'
import sys, base64, os, json
gen, adir = sys.argv[1], sys.argv[2]
manifest = [("plant", "plant.glb")]   # (registry key, file) -- add rows as assets grow
assets = {}
for key, fname in manifest:
    with open(os.path.join(adir, fname), "rb") as f:
        assets[key] = "data:model/gltf-binary;base64," + base64.b64encode(f.read()).decode()
with open(gen, "w") as f:
    f.write("// GENERATED by tools/blender/build.sh -- do not hand-edit.\n")
    f.write("window.SO_ASSETS=" + json.dumps(assets) + ";\n")
print("wrote", gen, "(", sum(len(v) for v in assets.values()), "b64 chars )")
PY
